channels:
  - conda-forge
  - defaults
  - anaconda
  - auto
dependencies:
  - openjdk
  - maven
  - make
  - z5py
  - python == 3.7.9
  - scikit-image
  - pytest
  - zarr >= 2.4.0
  - pip
  - go
  - rust
  - openssl
  - crypto
  - pip:
      - pyn5
